repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-vcs-permalinks
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [ '--allow-missing-credentials']  # Avoid failure on BuildKite
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
# Python formatters
-   repo: local
    hooks:
      - id: black
        name: Black (python formatter)
        entry: poetry run black src/ tests/
        language: system
        types: [python]
        require_serial: true
-   repo: local
    hooks:
      - id: isort
        name: isort (python import sorter)
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
# Build script linters
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
    -   id: shellcheck
        name: Shellcheck
        args: ["-f", "gcc"]  # output filename:linenum:colnum (clickable)
-   repo: https://github.com/hadolint/hadolint
    rev: v1.23.0
    hooks:
      - id: hadolint
        name: Hadolint (Dockerfile checker)
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check
        name: Docker-compose.yaml validity
# Linters that spot ongoing errors/warnings that need fixing/tuning
# -   repo: local
#     hooks:
#     -   id: mypy
#         name: mypy
#         entry: poetry run mypy --
#         types: [python]
#         language: system  # force running outside venv to find poetry
#         pass_filenames: True
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: poetry run flake8 --output-file test_results/flake8.txt --tee src/ tests/
        types: [python]
        language: system
        pass_filenames: False
# -   repo: local
#     hooks:
#     -   id: vulture
#         name: Vulture (Dead code checker)
#         entry: poetry run vulture
#         language: system
#         types: [python]
# TODO: Look up https://pypi.org/project/dependency-check/ for addition here
# See also:
# https://github.com/DmytroLitvinov/awesome-flake8-extensions
# https://github.com/vintasoftware/python-linters-and-code-analysis
# https://github.com/eliasgranderubio/dagda
# https://github.com/anchore/anchore-engine (docker)
# https://github.com/seddonym/import-linter ("forbid X.py from depending on boto3")
